version: '3.8'

services:
  goapi:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@database:5432/postgres
    depends_on:
      migrator:
        condition: service_healthy
